apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-websocket
  name: go-websocket
  namespace: kube-system
spec:
  ports:
  - port: 1234
    name: http1
    protocol: TCP
    targetPort: 1234
    nodePort: 32080
  selector:
    app: go-websocket
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-websocket
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-websocket
  template:
    metadata:
      labels:
        app: go-websocket
    spec:
      containers:
      - name: go-websocket
        image: docker.io/library/go-websocket:0.1
        command: ["/bin/sh","-ce","./websocket"]
        volumeMounts:
        - mountPath: /etc/rancher/k3s/k3s.yaml
          name: k3s-yaml
        - mountPath: /var/log/go-websocket.log
          name: log
      volumes:
        - name: k3s-yaml
          hostPath:
            path: /etc/rancher/k3s/k3s.yaml
        - name: log
          hostPath:
            path: /var/log/go-websocket.log
