apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-websocket-serviceaccount
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: frontend-websocket-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: frontend-websocket-serviceaccount
  namespace: kube-system
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: ""
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-websocket
  name: frontend-websocket
  namespace: kube-system
spec:
  ports:
  - port: 1234
    name: http1
    protocol: TCP
    targetPort: 1234
    nodePort: 32080
  selector:
    app: frontend-websocket
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-websocket
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-websocket
  template:
    metadata:
      labels:
        app: frontend-websocket
    spec:
      serviceAccountName: frontend-websocket-serviceaccount
      nodeSelector:
        k3s.io/hostname: k3s-master
      containers:
      - name: frontend-websocket
        image: docker.io/library/frontend-websocket:1.0
        imagePullPolicy: Never
        command: ["/bin/sh","-ce","./main"]
